### ISSUE TITLE
gyp: binding.gyp not found

### ISSUE THREAD

**Issue by ArthurAttout** [MatthD/node-libxml#30]
When attempting to `npm i node-libxml` the following error occurs : 

```
PS D:\wrkfldr> npm i node-libxml
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

> node-libxml@5.0.3 install D:\wrkfldr\node_modules\node-libxml
> node-gyp-build

gyp: binding.gyp not found (cwd: D:\wrkfldr\node_modules\node-libxml) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\wrkfldr\node_modules\node-gyp\lib\configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\wrkfldr\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\wrkfldr\node_modules\node-libxml
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v9.4.1
gyp ERR! not ok
```

**Comment by jeanfortheweb** [comment]
same here, not sure what to do

**Comment by MatthD** [comment]
Hello there , seems ou are on windows, what architecture do you use ?

It's not available for win32 only x64 or arm64 windows

https://www.npmjs.com/package/node-libxml?activeTab=code

I just added the missing files to npm packages for fallback build, could one of you clone this repo, and do this -> https://github.com/MatthD/node-libxml#contribute

then add binary inside `prebuild/${arch}` (for you windows x64) here, I will publish them
